In [87]:
!python -m pip install elasticsearch

     |████████████████████████████████| 325 kB 7.8 MB/s eta 0:00:01


In [1]:
'''
embedding non supervise + corpus sur disque .....
pip install --upgrade gensim 


Implementation (algo mikolov)

PV-DM is consistently better than PV-DBOW. PVDM alone can achieve results close to many results
in this paper (see Table 2). For example, in IMDB,
PV-DM only achieves 7.63%. The combination of
PV-DM and PV-DBOW often work consistently better (7.42% in IMDB) and therefore recommended.
• Using concatenation in PV-DM is often better than
sum. In IMDB, PV-DM with sum can only achieve
8.06%. Perhaps, this is because the model loses the
ordering information.
• It’s better to cross validate the window size. A good
guess of window size in many applications is between
5 and 12. In IMDB, varying the window sizes between
5 and 12 causes the error rate to fluctuate 0.7%.
• Paragraph Vector can be expensive, but it can be done
in parallel at test time. On average, our implementation takes 30 minutes to compute the paragraph vectors of the IMDB test set, using a 16 core machine
(25,000 documents, each document on average has
230 words).

There are two implementations:

Paragraph Vector - Distributed Memory (PV-DM)

Paragraph Vector - Distributed Bag of Words (PV-DBOW)

PV-DM is analogous to Word2Vec CBOW. The doc-vectors are obtained by training a neural network
on the synthetic task of predicting a center word based an average of both context word-vectors
and the full document’s doc-vector.

PV-DBOW is analogous to Word2Vec SG. The doc-vectors are obtained by training a neural network
on the synthetic task of predicting a target word just from the full document’s doc-vector.
(It is also common to combine this with skip-gram testing, using both the doc-vector and nearby word-vectors
to predict a single target word, but only one at a time.)

dm ({1,0}, optional) – Defines the training algorithm. If dm=1, ‘distributed memory’ (PV-DM) is used. 
Otherwise, distributed bag of words (PV-DBOW) is employed.

Note: dm defines the training algorithm. If dm=1 means ‘distributed memory’ (PV-DM)
and dm =0 means ‘distributed bag of words’ (PV-DBOW).
Distributed Memory model preserves the word order in a document 
whereas Distributed Bag of words just uses the bag of words approach, which doesn’t preserve any word order.

'''

''

''

In [2]:
'''

Gensim fournit également une fonction pour un prétraitement plus efficace du corpus. Dans ce type de prétraitement, nous pouvons convertir un document en une liste de jetons minuscules. Nous pouvons également ignorer les jetons qui sont trop courts ou trop longs. Une telle fonction est gensim.utils.simple_preprocess (doc, deacc = False, min_len = 2, max_len = 15) .

gensim. utils.simple_preprocess () fucntion

Gensim fournit cette fonction pour convertir un document en une liste de les jetons minuscules
et aussi pour ignorer les jetons trop courts ou trop longs. Il a les paramètres suivants -

doc (str)
Il fait référence au document d'entrée sur lequel le prétraitement doit être appliqué.

deacc (booléen, facultatif)
Ce paramètre est utilisé pour supprimer les marques d'accentuation des jetons. 
Il utilise deaccent () pour ce faire.

min_len (int, facultatif)
Avec l'aide de ce paramètre, nous pouvons définir la longueur minimale de un jeton. Les jetons plus courts que la longueur définie seront supprimés.

max_len (int, facultatif)
Avec l'aide de ce paramètre, nous pouvons définir la longueur maximale d'un jeton.
Les jetons plus longs que la longueur définie seront supprimés.

La sortie de cette fonction serait les jetons extraits du document d'entrée.

import corpora 
dictionary = corpora.Dictionary (processor_corpus)
print (dictionnaire)

donne
Dictionnaire (25 jetons uniques: [ 'ordinateur ', 'opinion ', 'réponse ' ' , 'survey ', 'system '] ...)
Cela montre que dans notre corpus il y a 25 différences ent tokens dans ce gensim.corpora.Dictionary.

Nous pouvons utiliser le dictionnaire pour transformer des documents tokenisés
en ces vecteurs à 5 dimension comme suit -de 0 à 25 (trivial )

pprint.pprint (dictionary.token2id)
ce qui donne { ' binaire ': 11, ' ordinateur ': 0, ' erreur ': 7, ' génération ': 12, ' graphique ': 16, 
' intersection ': 17, ' iv ': 19, ' mesure ': 8, ' mineurs ': 20, ' opinion ': 1, ' ordre ': 21,
' chemins ': 18, ' perçu ': 9, 'quasi ': 22, 'random ': 13, 'relation ': 10, 'response ': 2,
'survey ': 3, 'system ': 4, 'heure ': 5, 'arbres ': 14, 'unordered ': 15, 'utilisateur ': 6,
'puits ': 23, 'largeurs ': 24}

Et de la même manière, nous pouvons créer la représentation sac de mots pour un document comme suit -

BoW_corpus = [dictionary.doc2bow (text) for text in processor_corpus]
ce qui donne

pprint.pprint (BoW_corpus)
Et de la même manière, nous pouvons créer la représentation sac de mots pour un document comme suit -
[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1)],
[(2, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1),(10, 1)],
[(11, 1) , (12, 1), (13, 1), (14, 1), (15, 1)],
[(14, 1), (16, 1), (17, 1), (18, 1) ]
, [(14, 1), (16, 1), (19, 1), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1) ],
]
tf-idf modèle transformer la chaîne «tree graph».


exemple 
text_tokens = [[texte pour texte dans doc.split ()] pour doc dans doc]
dict_LoS = corpora.Dictionary (text_tokens)

'''

""

''

In [3]:
"""
Créer un corpus BoW (bag of word)
Dans Gensim, le corpus contient le mot id et son fréquence dans chaque document.
Nous pouvons créer un corpus BoW à partir d'une simple liste de documents et de fichiers texte.
Ce que nous devons faire est de transmettre la liste de mots tokenisés à l'objet nommé Dictionary.doc2bow () .


"""

""

''

In [4]:
"""
nettoyage Anglais 
Nous devons maintenant importer les mots vides et utilisez-les -

from nltk.corpus import stopwords
stop_words = stopwords.words ( 'english ')
stop_words.extend ([ 'from ', 'subject ', ' re ', ' edu ', ' use '])



"""
""

''

In [5]:
"""
reduire pour affichage
Tracer des vecteurs de mots à l'aide de PCA
Tout d'abord, nous devons récupérer tous les vecteurs d'un modèle entraîné comme suit -

Z = model [model.wv.vocab]

Ensuite, nous devons créer un modèle PCA 2D de vecteurs de mots en utilisant la classe PCA comme suit -

pca = PCA (n_components = 2)
result = pca.fit_transform (Z)

Maintenant, nous pouvons tracer la projection résultante en utilisant le matplotlib comme suit -

Pyplot.scatter (result [:, 0], result [:, 1])

On peut aussi annoter les points sur le graphique avec les mots lui-même.
Tracez la projection résultante en utilisant le matplotlib comme suit -

words = list (model.wv.vocab)
for i, word in enumerate (words):
    pyplot.annotate ( word, xy = (result [i, 0], result [i, 1]))
    



"""

""

''

In [6]:
"""
Former le Doc2Vec
Pour entraîner le modèle, nous avons besoin du document balisé qui peut être créé en utilisant
models.doc2vec.TaggedDcument ( ) comme suit -

def tagged_document (list_of_list_of_words):
    pour i, list_of_words dans enumerate (list_of_list_of_words):

        yield gensim.models.doc2vec.TaggedDocument (list_of_words, [i])
    
    
data_for_training = list (tagged_document (data))


"""

""

''

In [7]:
"""
Un fichiers (on peut anchainer les fichiers ....)

class MySentences(object):
    def __init__(self, dirname):
        self.dirname = dirname
 
    def __iter__(self):
        for fname in os.listdir(self.dirname):
            for line in open(os.path.join(self.dirname, fname)):
                yield line.split()
 
sentences = MySentences('/some/directory') # a memory-friendly iterable
model = gensim.models.Word2Vec(sentences)


ou

class MyCorpus(object):
    def __iter__(self):
    for line in open('mycorpus.txt'):
        # assume there's one document per line, tokens separated by whitespace
        yield dictionary.doc2bow(line.lower().split())
"""
""

''

In [8]:
"""
class exemple

class Doc2VecTrainer(object):
    def __init__(self, train_corpus):
        self.train_corpus = train_corpus

    def run(self):
        print('app started')

        cores = multiprocessing.cpu_count()
        print('num of cores is %s' % cores)
        gc.collect()
        if load_existing:
            print('loading an exiting model')
            model = Doc2Vec.load(PATH_TO_EXISTING_MODEL)
        else:
            print('reading training corpus from %s' % self.train_corpus)
            corpus_data = MyCorpus(self.train_corpus)
            
            model = Doc2Vec(size=model_dimensions, window=10, min_count=3, sample=1e-4, negative=5, workers=cores, dm=1)
            print('building vocabulary...')
            model.build_vocab(corpus_data)

            model.train(corpus_data, total_examples=model.corpus_count, epochs=20)
            
            model.save(doc2vec_model)
            model.save_word2vec_format(word2vec_model)

        print('total docs learned %s' % (len(model.docvecs)))

"""
""

''

In [9]:
"""
similarite cos

from gensim.matutils import softcossim
from gensim import corpora

sent_1 = 'Sachin is a cricket player and a opening batsman'.split()
sent_2 = 'Dhoni is a cricket player too He is a batsman and keeper'.split()
sent_3 = 'Anand is a chess player'.split()

# Prepare the similarity matrix
similarity_matrix = fasttext_model300.similarity_matrix(dictionary, tfidf=None,
                                                        threshold=0.0, exponent=2.0, nonzero_limit=100)

# Prepare a dictionary and a corpus.
documents = [sent_1, sent_2, sent_3]
dictionary = corpora.Dictionary(documents)

# Convert the sentences into bag-of-words vectors.
sent_1 = dictionary.doc2bow(sent_1)
sent_2 = dictionary.doc2bow(sent_2)
sent_3 = dictionary.doc2bow(sent_3)

# Compute soft cosine similarity
print(softcossim(sent_1, sent_2, similarity_matrix))
#> 0.7868705819999783

print(softcossim(sent_1, sent_3, similarity_matrix))
#> 0.6036445529268666

print(softcossim(sent_2, sent_3, similarity_matrix))
#> 0.60965453519611

ou encore
# Compute cosine distance between two words.
print(fasttext_model300.distance('king', 'queen'))
#> 0.22957539558410645


# Compute cosine distances from given word or vector to all words in `other_words`.
print(fasttext_model300.distances('king', ['queen', 'man', 'woman']))
#> [0.22957546 0.465837   0.547001  ]


"""
""

''

In [10]:
"""
ajout de nouvelle donnee

# Update the model with new data.
model.build_vocab(data_part2, update=True)

model.train(data_part2, total_examples=model.corpus_count, epochs=model.iter)



"""


""

''

In [11]:
"""
amelioration  qualite faire BoG and DM

Le and Mikolov note that combining a paragraph vector from Distributed Bag of Words (DBOW)
and Distributed Memory (DM) improves performance. 
We will follow, pairing the models together for evaluation.
Here, we concatenate the paragraph vectors obtained from each model with the help of a thin wrapper class
included in a gensim test module.
(Note that this a separate, later concatenation of output-vectors
than the kind of input-window-concatenation enabled by the dm_concat=1 mode above.)


from gensim.test.test_doc2vec import ConcatenatedDoc2Vec

models_by_name['dbow+dmm'] = ConcatenatedDoc2Vec([simple_models[0], simple_models[1]])
models_by_name['dbow+dmc'] = ConcatenatedDoc2Vec([simple_models[0], simple_models[2]])







"""

""

''

In [17]:
import sys, os
sys.version_info

sys.version_info(major=3, minor=7, micro=10, releaselevel='final', serial=0)

In [21]:
import gensim

In [90]:
#Import all the dependencies
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from nltk.tokenize import word_tokenize
import nltk


#nltk.download ()
#nltk.download('averaged_perceptron_tagger') # indispensable pour word_tokenize ?

# on tag

data = ["I love machine learning. Its awesome.",
        "I love coding in python",
        "I love building chatbots",
        "they chat amagingly well"]

tagged_data = [TaggedDocument(words=word_tokenize(_d.lower()), tags=[str(i)]) for i, _d in enumerate(data)]

# on  train et on sauve
max_epochs = 200
vec_size = 20
alpha = 0.025

model = Doc2Vec(vector_size=vec_size,
                alpha=alpha, 
                min_alpha=0.00025,
                min_count=1, # on peur retirer les mots qui se repete peu
                dm =1)
  
model.build_vocab(tagged_data)

for epoch in range(max_epochs):
    print('iteration {0}'.format(epoch))
    model.train(tagged_data,
                total_examples=model.corpus_count,
                epochs=model.iter)
    # decrease the learning rate
    model.alpha -= 0.0002
    # fix the learning rate, no decay
    model.min_alpha = model.alpha

model.save("d2v.model")
print("Model Saved")

iteration 0
iteration 1
iteration 2
iteration 3
iteration 4
iteration 5
iteration 6
iteration 7
iteration 8
iteration 9
iteration 10
iteration 11
iteration 12
iteration 13
iteration 14
iteration 15
iteration 16
iteration 17
iteration 18
iteration 19
iteration 20
iteration 21
iteration 22
iteration 23
iteration 24
iteration 25
iteration 26
iteration 27
iteration 28
iteration 29
iteration 30
iteration 31
iteration 32
iteration 33
iteration 34
iteration 35
iteration 36
iteration 37
iteration 38
iteration 39
iteration 40
iteration 41
iteration 42
iteration 43
iteration 44
iteration 45
iteration 46
iteration 47


/home/patrick/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:36: DeprecationWarning: Call to deprecated `iter` (Attribute will be removed in 4.0.0, use self.epochs instead).


iteration 48
iteration 49
iteration 50
iteration 51
iteration 52
iteration 53
iteration 54
iteration 55
iteration 56
iteration 57
iteration 58
iteration 59
iteration 60
iteration 61
iteration 62
iteration 63
iteration 64
iteration 65
iteration 66
iteration 67
iteration 68
iteration 69
iteration 70
iteration 71
iteration 72
iteration 73
iteration 74
iteration 75
iteration 76
iteration 77
iteration 78
iteration 79
iteration 80
iteration 81
iteration 82
iteration 83
iteration 84
iteration 85
iteration 86
iteration 87
iteration 88
iteration 89
iteration 90
iteration 91
iteration 92
iteration 93
iteration 94
iteration 95
iteration 96
iteration 97
iteration 98
iteration 99
iteration 100
iteration 101
iteration 102
iteration 103
iteration 104
iteration 105
iteration 106
iteration 107
iteration 108
iteration 109
iteration 110
iteration 111
iteration 112
iteration 113
iteration 114
iteration 115
iteration 116
iteration 117
iteration 118
iteration 119
iteration 120
iteration 121
iteration 122
it

In [92]:
from gensim.models.doc2vec import Doc2Vec

model= Doc2Vec.load("d2v.model")

dico = model.wv.vocab


dico.keys()

dict_keys(['i', 'love', 'machine', 'learning', '.', 'its', 'awesome', 'coding', 'in', 'python', 'building', 'chatbots', 'they', 'chat', 'amagingly', 'well'])

In [22]:
from gensim.models.doc2vec import Doc2Vec

model= Doc2Vec.load("d2v.model")



#to find the vector of a document which is not in training data
test_data = word_tokenize("I love chatbots".lower())

v1 = model.infer_vector(test_data)
print("V1_infer", v1)
print ()
# to find most similar doc using tags
similar_doc = model.docvecs.most_similar('1')
print('similar_doc =',similar_doc)

print ()


# to find vector of doc in training data using tags or in other words, printing the vector of document at index 1 in training data
print(model.docvecs['1'])

V1_infer [-0.00564685  0.01462928 -0.01748178 -0.00022416  0.00809241 -0.0129272
  0.00882894 -0.01006111  0.01500504 -0.01217108 -0.02726755 -0.00573638
  0.01094585 -0.00329853 -0.01772864 -0.0081103  -0.01087801  0.01676391
 -0.02984307  0.01281742]

similar_doc = [('0', 0.9640241861343384), ('2', 0.9434124231338501), ('3', 0.9273204803466797)]

[-0.13717967 -0.09493966 -0.06150101 -0.1094641  -0.07383767 -0.0083202
  0.06344301  0.12452457 -0.0131894  -0.05017306  0.04211924 -0.0159562
  0.05519256  0.02529985 -0.01723339  0.05578071 -0.08192607  0.04602431
  0.14798976  0.03867978]


In [3]:
# pour gagner de la place apres train
model.delete_temporary_training_data(keep_doctags_vectors=True, keep_inference=True)

In [ ]:
"""
loading data from a file ???
"""

import smart_open

def read_corpus(fname, tokens_only=False):
    with smart_open.open(fname, encoding="iso-8859-1") as f:
        for i, line in enumerate(f):
            tokens = gensim.utils.simple_preprocess(line)
            if tokens_only:
                yield tokens
            else:
                # For training data, add tags
                yield gensim.models.doc2vec.TaggedDocument(tokens, [i])


train_corpus = list(read_corpus(lee_train_file))
test_corpus = list(read_corpus(lee_test_file, tokens_only=True))

In [78]:
#Import all the dependencies
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from nltk.tokenize import word_tokenize
import nltk


#nltk.download ()
#nltk.download('averaged_perceptron_tagger') # indispensable pour word_tokenize ?

# on tag
data = ["I love machine learning. Its awesome.",
        "I love coding in python",
        "I love building chatbots",
        "they chat amagingly well"]

#tagged_data = [TaggedDocument(words=word_tokenize(_d.lower()), tags=[str(i)]) for i, _d in enumerate(data)]

def lire_tagged_data (data) :
    #liste_tagged_data = []
    for i, _d in enumerate(data) :
        ligne_tagged = TaggedDocument(words=word_tokenize(_d.lower()), tags=[str(i)])
        #liste_tagged_data.append (ligne_tagged)
        yield ligne_tagged 
    return 

#tagged_data = lire_tagged_data (data)

def creation_bloc_tagged_data (data, debut, fin) :
    liste_tagged_data = []
    fin = min (len(data), fin)
    for i in range(debut, fin) :
        _d = data [i]
        ligne_tagged = TaggedDocument(words=word_tokenize(_d.lower()), tags=[str(i)])
        liste_tagged_data.append(ligne_tagged)
        continue
    return liste_tagged_data
      


# creation d un model
max_epochs = 200
vec_size = 20
alpha = 0.025

model = Doc2Vec(vector_size=vec_size,
                alpha=alpha, 
                min_alpha=0.00025,
                min_count=1, # on peur retirer les mots qui se repete peu
                dm =1)

# calculer le dictionnaire de mot avec un iterateur en entree (lire_tagged_data (data))
  
model.build_vocab(lire_tagged_data (data))



 
        
        
    
    
    
    
def apprentissage_par_bloc (model, bloc, max_epochs) :

    for epoch in range(max_epochs):
        print('iteration {0}'.format(epoch))
        model.train(bloc,
                    total_examples=model.corpus_count,
                    epochs=model.iter)
        # decrease the learning rate
        model.alpha -= 0.0002
        # fix the learning rate, no decay
        model.min_alpha = model.alpha
    return model


def data_by_bloc (data, taille_bloc = 2) :
    
    taille_data = len(data)
    
    # bouclage pour obtenir une suite de bloc de data
    for debut in range (0, taille_data, taille_bloc ) :
        fin = debut + taille_bloc
        if fin > taille_data :
            fin = taille_data
        bloc = creation_bloc_tagged_data (data, debut, fin)
        yield bloc
    return

for bloc in data_by_bloc (data, taille_bloc = 2) :
    model = apprentissage_par_bloc (model, bloc, max_epochs)
    continue   
    
        
    

model.save("d3v.model")
print("Model Saved")

iteration 0
iteration 1
iteration 2
iteration 3
iteration 4
iteration 5
iteration 6
iteration 7
iteration 8
iteration 9
iteration 10
iteration 11
iteration 12
iteration 13
iteration 14
iteration 15
iteration 16
iteration 17
iteration 18
iteration 19
iteration 20
iteration 21
iteration 22
iteration 23
iteration 24
iteration 25
iteration 26
iteration 27
iteration 28
iteration 29
iteration 30
iteration 31
iteration 32
iteration 33
iteration 34
iteration 35
iteration 36
iteration 37
iteration 38
iteration 39
iteration 40
iteration 41
iteration 42
iteration 43
iteration 44
iteration 45
iteration 46
iteration 47
iteration 48
iteration 49


/home/patrick/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:70: DeprecationWarning: Call to deprecated `iter` (Attribute will be removed in 4.0.0, use self.epochs instead).


iteration 50
iteration 51
iteration 52
iteration 53
iteration 54
iteration 55
iteration 56
iteration 57
iteration 58
iteration 59
iteration 60
iteration 61
iteration 62
iteration 63
iteration 64
iteration 65
iteration 66
iteration 67
iteration 68
iteration 69
iteration 70
iteration 71
iteration 72
iteration 73
iteration 74
iteration 75
iteration 76
iteration 77
iteration 78
iteration 79
iteration 80
iteration 81
iteration 82
iteration 83
iteration 84
iteration 85
iteration 86
iteration 87
iteration 88
iteration 89
iteration 90
iteration 91
iteration 92
iteration 93
iteration 94
iteration 95
iteration 96
iteration 97
iteration 98
iteration 99
iteration 100
iteration 101
iteration 102
iteration 103
iteration 104
iteration 105
iteration 106
iteration 107
iteration 108
iteration 109
iteration 110
iteration 111
iteration 112
iteration 113
iteration 114
iteration 115
iteration 116
iteration 117
iteration 118
iteration 119
iteration 120
iteration 121
iteration 122
iteration 123
iteration 124


In [49]:
from gensim.models.doc2vec import Doc2Vec

model= Doc2Vec.load("d3v.model")

#to find the vector of a document which is not in training data
test_data = word_tokenize("they chat amagingly well".lower())

v1 = model.infer_vector(test_data)
print("V1_infer", v1)
print ()
# to find most similar doc using tags
similar_doc = model.docvecs.most_similar('3')
print('similar_doc =',similar_doc)

print ()
# to find vector of doc in training data using tags or in other words, printing the vector of document at index 1 in training data
print(model.docvecs['0'])

V1_infer [ 0.22569653  0.28750235  0.02401031 -0.0108829   0.17088532  0.04682619
 -0.11734542 -0.18317683 -0.0057466   0.39737746  0.09157835  0.34125048
 -0.2888558  -0.40479952 -0.21948878 -0.17755204  0.35153478  0.14097649
 -0.29146546 -0.07713759]

similar_doc = [('2', 0.999789834022522), ('1', -0.9530922174453735), ('0', -0.9607970714569092)]

[-0.1070747  -0.11949181 -0.03749743 -0.00871333 -0.07253049  0.01190558
  0.07141125  0.09373917  0.03083587 -0.14086495 -0.03564801 -0.07839429
  0.10092853  0.10344115  0.0801303   0.08149958 -0.13921219 -0.00826297
  0.1290821   0.06467713]


In [ ]:
'''

V1_infer [-0.00564685  0.01462928 -0.01748178 -0.00022416  0.00809241 -0.0129272
  0.00882894 -0.01006111  0.01500504 -0.01217108 -0.02726755 -0.00573638
  0.01094585 -0.00329853 -0.01772864 -0.0081103  -0.01087801  0.01676391
 -0.02984307  0.01281742]

similar_doc = [('0', 0.9640241861343384), ('2', 0.9434124231338501), ('3', 0.9273204803466797)]

[-0.13717967 -0.09493966 -0.06150101 -0.1094641  -0.07383767 -0.0083202
  0.06344301  0.12452457 -0.0131894  -0.05017306  0.04211924 -0.0159562
  0.05519256  0.02529985 -0.01723339  0.05578071 -0.08192607  0.04602431
  0.14798976  0.03867978]
  
'''
''

In [28]:
import numpy as np
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine

A = np.array(
[[0, 1, 0, 0, 1],
[0, 1, 0, 0, 1],
[1, 0, 0, 0, 1]])

dist_out = pairwise_distances(A, metric="cosine")
dist_out

array([[0.00000000e+00, 2.22044605e-16, 5.00000000e-01],
       [2.22044605e-16, 0.00000000e+00, 5.00000000e-01],
       [5.00000000e-01, 5.00000000e-01, 0.00000000e+00]])

In [27]:
pairwise_distances(A, metric="cosine")

array([[0.00000000e+00, 2.22044605e-16, 5.00000000e-01],
       [2.22044605e-16, 0.00000000e+00, 5.00000000e-01],
       [5.00000000e-01, 5.00000000e-01, 0.00000000e+00]])

In [32]:
A = np.array(
[[0, 1, ],
[1, 0,]])

dist_out = pairwise_distances(A, metric="cosine")
dist_out

array([[0., 1.],
       [1., 0.]])

In [33]:
A = np.array(
[[1, 1, ],
[-1, -1,]])

dist_out = pairwise_distances(A, metric="cosine")
dist_out

array([[0., 2.],
       [2., 0.]])

In [34]:
A = np.array(
[[2, 2, ],
[-1, -1,]])

dist_out = pairwise_distances(A, metric="cosine")
dist_out

array([[0., 2.],
       [2., 0.]])

In [35]:
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse

A =  np.array([[0, 1, 0, 0, 1], [0, 0, 1, 1, 1],[1, 1, 0, 1, 0]])
A_sparse = sparse.csr_matrix(A)

similarities = cosine_similarity(A_sparse)
print('pairwise dense output:\n {}\n'.format(similarities))
print ()
#also can output sparse matrices
similarities_sparse = cosine_similarity(A_sparse,dense_output=False)
print('pairwise sparse output:\n {}\n'.format(similarities_sparse))

pairwise dense output:
 [[1.         0.40824829 0.40824829]
 [0.40824829 1.         0.33333333]
 [0.40824829 0.33333333 1.        ]]


pairwise sparse output:
   (0, 1)	0.408248290463863
  (0, 2)	0.408248290463863
  (0, 0)	0.9999999999999998
  (1, 0)	0.408248290463863
  (1, 2)	0.3333333333333334
  (1, 1)	1.0000000000000002
  (2, 1)	0.3333333333333334
  (2, 0)	0.408248290463863
  (2, 2)	1.0000000000000002



In [50]:
A = np.array(
[[2, 2, 3],
[-1, -1, 3]])


In [44]:
similarities = cosine_similarity(A,dense_output=False)
print('pairwise  output:\n {}\n'.format(similarities))

pairwise  output:
 [[ 1. -1.]
 [-1.  1.]]



In [ ]:
m = np.array([ V1_infer,V2_infer ])
A

In [43]:
similarities_sparse = cosine_similarity(A_sparse,dense_output=False)
print('pairwise sparse output:\n {}\n'.format(similarities_sparse))

pairwise sparse output:
   (0, 1)	-0.9999999999999998
  (0, 0)	0.9999999999999998
  (1, 1)	0.9999999999999998
  (1, 0)	-0.9999999999999998



<2x2 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [62]:
V1_infer = [ 0.22569653,  0.28750235,  0.02401031, -0.0108829,   0.17088532,  0.04682619,
 -0.11734542, -0.18317683, -0.0057466,   0.39737746,  0.09157835,  0.34125048,
 -0.2888558,  -0.40479952, -0.21948878, -0.17755204,  0.35153478,  0.14097649,
 -0.29146546, -0.07713759,]
len(V1_infer)

20

In [63]:
V2_infer = [-0.1070747,  -0.11949181, -0.03749743, -0.00871333, -0.07253049,  0.01190558,
  0.07141125,  0.09373917,  0.03083587, -0.14086495, -0.03564801, -0.07839429,
  0.10092853,  0.10344115,  0.0801303,   0.08149958, -0.13921219, -0.00826297,
  0.1290821,   0.06467713,]

len(V2_infer)

20

In [68]:
m = np.array([ V1_infer,V2_infer ])

m_sparse = sparse.csr_matrix(m)

m_sparse

<2x20 sparse matrix of type '<class 'numpy.float64'>'
	with 40 stored elements in Compressed Sparse Row format>

In [73]:

similarities = cosine_similarity(m,dense_output=True)
print('pairwise  output:\n {}\n'.format(similarities))

pairwise  output:
 [[ 1.         -0.95425256]
 [-0.95425256  1.        ]]



In [77]:
V1_infer = [ 0.22569653,  0.28750235,  0.02401031, -0.0108829,   0.17088532,  0.04682619,
 -0.11734542, -0.18317683, -0.0057466,   0.39737746,  0.09157835,  0.34125048,
 -0.2888558,  -0.40479952, -0.21948878, -0.17755204,  0.35153478,  0.14097649,
 -0.29146546, -0.07713759,]

V2_infer = [-0.1070747,  -0.11949181, -0.03749743, -0.00871333, -0.07253049,  0.01190558,
  0.07141125,  0.09373917,  0.03083587, -0.14086495, -0.03564801, -0.07839429,
  0.10092853,  0.10344115,  0.0801303,   0.08149958, -0.13921219, -0.00826297,
  0.1290821,   0.06467713,]

m = np.array([ V1_infer,V1_infer ])

similarities = cosine_similarity(m,dense_output=True)

1.0 - similarities [0] [1]

3.3306690738754696e-16

In [86]:
from nltk.tokenize import word_tokenize

ponctuation = {"." : None,
                "'" :None,
                '?' : None,
                '-'  : None,
                ";"  :None,
                '(' : None,
                ')' : None,
                '#' : None,
                '=' : None,
                '!' : None,
                '&' : None,
                '*' : None,
                '@' : None,
                '%' : None,
                '"' : None,
                '+' : None,

               }
mot1 = "test"
mot2 = "du_test"

for caractere in ponctuation.keys() :
    motTest = mot1+caractere+mot2
    r = word_tokenize (mot)
    isFind = False
    for n in r :
        if n in ponctuation :
            print ("caractere ", caractere, ' OK')
            isFind = True
            continue
        continue
    if not isFind :
        print ("caractere ", caractere, ' KO ###################')
        
    continue
    

        
        
            

caractere  .  OK
caractere  '  OK
caractere  ?  OK
caractere  -  OK
caractere  ;  OK
caractere  (  OK
caractere  )  OK
caractere  #  OK
caractere  =  OK
caractere  !  OK
caractere  &  OK
caractere  *  OK
caractere  @  OK
caractere  %  OK
caractere  "  OK
caractere  +  OK


In [83]:
word_tokenize ('test et')

['test', 'et']

In [88]:
t1 =  "t1"
t2 = 't2'
t3 = 't3'
t4 = 't4'
t5 = 't5'

%time t = t1+t2+t3+t4+t5

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.53 µs


In [89]:
l = [t1, t2, t3, t4, t5]
%time t = ''.join (l)

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 5.72 µs
